### PR TITLE
Replace default.nix with flake.nix

### PR DESCRIPTION
**Pull request by ThetaSinner**

### CODE REVIEW

**Comment by matthme** [comment]
I'm currently getting this error when trying to run `npm run tauri dev` in this nix shell:
```
[...]/target/debug/holochain-launcher-beta-2: error while loading shared libraries: libbz2.so.1: cannot open shared object file: No such file or directory
```
I'm not sure yet whether it also affects the hc_launch crate.

**Comment by matthme** [comment]
It's not that important as long as we don't aspire to build the launcher UI from within nix-shell (which I think we shouldn't anyway). I'm not using nix during development of the launcher anyway.

**Comment by ThetaSinner** [comment]
Good spot thanks. I've got this running under Linux now. There may be more libraries needed on MacOS but I'll sort that out if somebody wants it for something :) As you say, this is not being used for development currently

**Review by matthme — APPROVED** [review]
Looking good now, thanks!

**Review by steveej — APPROVED** [review]
according to a quick grep neither the `default.nix` isn't used anywhere but the technical transformation looks correct to me.

**Pull request merged**
