### PR TITLE
add hdi version and change version number of devhub to hdi version

### LINKED ISSUE #75: Make devhub name after hdi version instead of holochain version

### PR DESCRIPTION
**Pull request by matthme**
This would fix #75. However I feel like we should generally rethink how to organize version compatibility and also maybe add compatibility ranges instead of a 1:1 mapping between holochain version and hdk/hdi version.

### CODE REVIEW

**Comment by zippy** [comment]
Well, I think you are right, but I'm also ok with making progressive improvement.   I'd be fine with merging this for now, and waiting for the range stuff to happen at the same time as we add that to the bundle-format and to the dev-hub.

**Comment by guillemcordoba** [comment]
I like this, though I feel we should target v0.1 of hdi instead of v0.1.2. All v0.1.x of the hdi should be compatible with each other and with the holochain conductor that supports it. 

In general, I'd rather start expecting the correct behaviour of holochain core's versioning and releases and break early than work around its currently broken versioning and have to correct later.

**Comment by matthme** [comment]
Hmm...I think I agree that targeting v0.1 in general is a good idea but then there is no way to distinguish different versions of the devhub anymore. If the devhub gets upgraded to hc 0.0.165 or beyond, how would one notice?
I think there are two parts to it, one is knowing whether apps uploaded to the devhub will be compatible with it (if the hdi version of the devhub matters for that?) and the other is knowing whether that's the same devhub that you already uploaded your stuff last time and you can expect certain apps to be there.

**Comment by guillemcordoba** [comment]
Ah right haha then the devhub app id needs to be really tied to the holochain version no? Cause multiple holochain versions will be tied to the same hdi/hdk version.

**Pull request merged**
