### PR TITLE
Bump weekly 0.3-25

### PR DESCRIPTION
**Pull request by ThetaSinner**

### CODE REVIEW

**Review by matthme — APPROVED** [review]
Looking good. I noticed that we still have the dependencies scattered across multiple Cargo.toml files in this branch. In the develop branch most of the holochain dependencies are just [defined in the root level Cargo.toml](https://github.com/holochain/launcher/blob/95db96c42d2975afa7279a8217ad74dfcb85b103/Cargo.toml#L10) which makes it easier to bump.

**Comment by ThetaSinner** [comment]
Dependencies gathered into the root would be easier! It seems I was a bit premature putting this up for review, it had some build issues with API changes on the latest weekly version of Holochain. Working through those now.

Tauri also helpfully provide a NixOS flake example so I've updated the flake with their suggestions and I now seem to be able to build the Tauri deps inside Nix which is great :)

**Comment by matthme** [comment]
Cool :)
> I was a bit premature putting this up for review

Not as premature as my approval without actually trying to build it ;)

**Comment by ThetaSinner** [comment]
Well the build errors now seem to be Holochain...

**Comment by ThetaSinner** [comment]
It's passing on macos so that's progress. @matthme does this Holochain install step fail locally for you? It's working fine for me when I try to run just that piece

**Comment by matthme** [comment]
Holochain is compiling fine for me also. What's missing to get the launcher UI running is the holochain name in [this](https://github.com/holochain/launcher/blob/3c725e3e57c4e8bcef3c37d3ecfe1022dd5a6abd/crates/holochain_manager/src/versions/mod.rs#L59) line.

**Comment by matthme** [comment]
Btw a global search for `NEW_VERSION` shows you all places that require changes in case of a version bump (assuming there are no breaking changes and except the renaming of the binary in tauri.conf.json where it's not possible to add comments).

**Comment by matthme** [comment]
And hc launch also compiles fine. Can't test it though because I don't have any 0.3.x happ at the moment.

**Comment by ThetaSinner** [comment]
Thanks! PR is looking better but this build issue persists :/

**Comment by matthme** [comment]
Oh, I didn't even see that yet. Weird...it compiled fine on my Ubuntu 22.04 locally

**Comment by ThetaSinner** [comment]
Likewise on my WSL Ubuntu, and inside Nix

**Comment by matthme** [comment]
Good to merge for me. As said elsewhere I would not want to have the new runners on the develop branch before testing that it doesn't affect compatibility of the built executables with older OS but that doesn't matter for the weekly branch.

**Pull request merged**
